version: '3'
services:
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    ports:
      - 3001:4567
    environment:
      - PORT=4567
      - NODE_ENV=development
      - MONGO_USER=sanjeev
      - MONGO_PASSWORD=mypassword
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    