version: "3"
services:
  node-app:
    build: .

  mongo:
    image: mongo   #mongo database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db    # named volume이름은 volume section에 그 이름을 미리 등록해야 한다.

volumes:
  mongo-db:
