version: "3"
services:
  node-app:
    build: .
    depends_on:
      - mongo
    links:
      - redis
      - mongo

  mongo:
    image: mongo:6   #mongo database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db    # named volume이름은 volume section에 그 이름을 미리 등록해야 한다.
    ports:
      - 27017:27017

  redis:
    image: redis:7.0.10
    ports:
      - 6379:6379

volumes:
  mongo-db:
