version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    environment:
      - PORT=3456
      - NODE_ENV=development
      - MONGO_USER=sanjeev
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    ports:
      - 3001:3456
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword

