version: '3'
services:
  node-app:
    build: .
    ports:
      - "3001:4422"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    # environment:
    #   - PORT=4422
    env_file:
      - ./.env