version: '3'
services:
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    ports:
      - "3001:4567"
    environment:
      - PORT=4567
      - NODE_ENV=development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    command: npm run dev
