version: '3'
services:
  nginx:
    ports:
      - "3001:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    environment:
      - PORT=3456
      - NODE_ENV=development
      - MONGO_USER=sanjeev
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret

    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev


