version: '3'
services:
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: production
    ports:
      - 3001:4422
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    command: node index.js