### get all posts
GET http://localhost:3001/api/v1/posts

### create a post
POST http://localhost:3001/api/v1/posts
Content-Type: application/json

{
  "title":"my sixth post",
  "body":"body of sixth post"
}

### update a post
PATCH http://localhost:3001/api/v1/posts/6427271f0c0456918fc0b693
Content-Type: application/json

{
  "title":"my first post updated",
  "body":"body of first post"
}

### get a post
GET http://localhost:3001/api/v1/posts/643aefc5353267e956086920

### delete a post
DELETE  http://localhost:3001/api/v1/posts/643af022353267e95608692e

### sign up
POST http://localhost:3001/api/v1/users/signup
Content-Type: application/json

{
  "username":"w@x",
  "password":"w"
}

### sign up
POST http://localhost:3001/api/v1/users/signup
Content-Type: application/json

{
  "username":"jst0930@gmail.com",
  "password":"w"
}

### login
POST http://localhost:3001/api/v1/users/login
Content-Type: application/json

{
  "username":"w@w",
  "password":"w"
}

### login
POST http://localhost:3001/api/v1/users/login
Content-Type: application/json

{
  "username":"jst0930@gmail.com",
  "password":"w"
}

### get all users
GET http://localhost:3001/api/v1/users

### logout
POST http://localhost:3001/api/v1/users/logout


### api home
GET http://localhost:3001/api/v1