### get all posts
GET http://localhost:3001/api/v1/posts

### create a post
POST http://localhost:3001/api/v1/posts
Content-Type: application/json

{
  "title":"my second post",
  "body":"body of second post"
}

### update a post
PATCH http://localhost:3001/api/v1/posts/6428522b228e8f046deefb2c
Content-Type: application/json

{
  "title":"my first post updated",
  "body":"body of first post"
}

### get a post
GET http://localhost:3001/api/v1/posts/6428522b228e8f046deefb2c

### delete a post
DELETE  http://localhost:3001/api/v1/posts/6428522b228e8f046deefb2c

### sign up
POST http://localhost:3001/api/v1/users/signup
Content-Type: application/json

{
  "username":"John",
  "password":"test"
}

### login
GET http://localhost:3001/api/v1/users/login
Content-Type: application/json

{
  "username":"sanjeev",
  "password":"test"
}

### get all users
GET http://localhost:3001/api/v1/users
